export const images = {
    hero: {
        background: "/assets/himanshu_hero.jpg",
        profile: "/assets/home.jpeg",
        himanshuVideo: "/assets/himanshuvideo.mp4",
    },
    projects: {
        creatorScaling: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=2070&auto=format&fit=crop",
        brandFilms: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=2070&auto=format&fit=crop",
        tlr: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop",
    },
    fdi: {
        episode1: "https://images.unsplash.com/photo-1548613053-220e7530434d?q=80&w=2070&auto=format&fit=crop",
        episode2: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2144&auto=format&fit=crop",
    },
    playlist: {
        tlrIntro: "https://img.youtube.com/vi/xEt0_TFvKqc/maxresdefault.jpg",
        olaElectric: "https://img.youtube.com/vi/rEOx2SDIv7c/maxresdefault.jpg",
        fancode: "https://img.youtube.com/vi/Qq4wWHlgncw/maxresdefault.jpg",
        scaler: "https://img.youtube.com/vi/Ac7r4zkCuyk/maxresdefault.jpg",
        chara: "https://img.youtube.com/vi/vWW0MIXr__Y/maxresdefault.jpg",
        dunzo: "https://img.youtube.com/vi/4vOrJewXBQ8/maxresdefault.jpg",
        vfs: "https://img.youtube.com/vi/N105xZHCHck/maxresdefault.jpg",
        bluestone: "https://img.youtube.com/vi/CT9uUEg4Ep0/maxresdefault.jpg",
        coindcx: "https://img.youtube.com/vi/VPxs3SAJh2k/maxresdefault.jpg",
        hanuman: "https://img.youtube.com/vi/l7vIXb4d6mE/maxresdefault.jpg",
        foreignUniversities: "https://img.youtube.com/vi/uxcjLHjpRzE/maxresdefault.jpg",
        finnable: "https://img.youtube.com/vi/0pjOJZ_Dipo/maxresdefault.jpg",
        readyAssist: "https://img.youtube.com/vi/PCvGW2p-gDA/maxresdefault.jpg",
        convey: "https://img.youtube.com/vi/n_-nSJlapaM/maxresdefault.jpg",
        olaCase: "https://img.youtube.com/vi/hbfksNX5sDk/maxresdefault.jpg",
        google: "https://img.youtube.com/vi/2BEoWYk4x8w/maxresdefault.jpg",
        byejus: "https://img.youtube.com/vi/k0JrOj03Hec/maxresdefault.jpg",
        vizx: "https://img.youtube.com/vi/pV9OAafXrrM/maxresdefault.jpg",
        pw: "https://img.youtube.com/vi/isY4a634RIw/maxresdefault.jpg",
        documentary: "https://img.youtube.com/vi/yw5sLn-V4PA/maxresdefault.jpg",
        southAsia: "https://img.youtube.com/vi/1V1-UU4NYJ8/maxresdefault.jpg",
        scanx: "https://img.youtube.com/vi/V3s53qf-VkM/maxresdefault.jpg",
        flutter: "https://img.youtube.com/vi/vk3MkIdeN-0/maxresdefault.jpg",
        elevateX: "https://img.youtube.com/vi/w--BauI1g5U/maxresdefault.jpg",
        ambedkar: "https://img.youtube.com/vi/agBxrOrzFa8/maxresdefault.jpg",
        foreignPolicy: "https://img.youtube.com/vi/s6yp7yNpAEA/maxresdefault.jpg",
        animation: "https://img.youtube.com/vi/dHF14BLoUkI/maxresdefault.jpg",
        explainer: "https://img.youtube.com/vi/a_MANkTAvZM/maxresdefault.jpg",
        discord: "https://img.youtube.com/vi/rINK4Ce4gHQ/maxresdefault.jpg",
        abhiNiyu: "https://img.youtube.com/vi/bB_2Ov1pHew/maxresdefault.jpg",
        india2024: "https://img.youtube.com/vi/TI9JS2mHPjQ/maxresdefault.jpg",
        meta: "https://img.youtube.com/vi/sjHbLpl7iUE/maxresdefault.jpg",
        adEditing: "https://img.youtube.com/vi/tCligskSFbw/maxresdefault.jpg",
        podcast: "https://img.youtube.com/vi/fc0YGVc8Rg8/maxresdefault.jpg",
        khatu: "https://img.youtube.com/vi/LSKxE2QE4io/maxresdefault.jpg",
        logo: "https://img.youtube.com/vi/7fnQ94Zglmk/maxresdefault.jpg",
        product: "https://img.youtube.com/vi/vsNFFPkLmZk/maxresdefault.jpg",
        fcf: "https://img.youtube.com/vi/AwcU3LSw7V4/maxresdefault.jpg",
        socialMedia: "https://img.youtube.com/vi/FWyc9pgxcc8/maxresdefault.jpg",
        shorts: "https://img.youtube.com/vi/5euZi4tn71k/maxresdefault.jpg",
        poetry: "https://img.youtube.com/vi/CR7KX2xP2Fc/maxresdefault.jpg",
        kombucha: "https://img.youtube.com/vi/cpm2YtfOtEI/maxresdefault.jpg"
    }
};
